version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: npm run dev -- --host
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    command: uvicorn main:app --host 0.0.0.0 --reload
    